export type {
  SmtpSecurity,
  SmtpAccountDTO,
  TemplateDTO,
  RecipientDTO,
  CampaignDTO,
  CampaignRecipientDTO,
  SendLogDTO,
  SettingsDTO,
  Paged,
  SmtpTestResultDTO,
  DashboardDTO,
  ExternalImportResultDTO,
  CsvImportResultDTO,
  RecipientStatsDTO,
  CampaignStatus,
  BounceCategoryKey,
  BounceCategoryMeta,
  SuppressionReason,
  ReportOverviewDTO,
  BounceMatrixDTO,
  BounceSampleDTO,
  CampaignReportDTO,
  SuppressionDTO,
  SuppressionStatsDTO,
} from "@shared/types";

export { SPEED_OPTIONS, SCHEDULE_PRESETS, isValidEmail, nameFromEmail } from "@shared";
